language: java
jdk:
  - oraclejdk8
before_install:
  - git clone https://github.com/DTL-FAIRData/FAIRSearchEngine ~/fairsearchengine
  - cd ~/fairsearchengine
  - mvn installF
  - cd $TRAVIS_BUILD_DIR
after_success:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test org.jacoco:jacoco-maven-plugin:report coveralls:report
